version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: chakall-oracle-xe
    environment:
      - ORACLE_PWD=ChakallPassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - chakall-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "sys/ChakallPassword123@localhost:1521/XE", "as", "sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Adminer para administración de base de datos (opcional)
  adminer:
    image: adminer:latest
    container_name: chakall-adminer
    ports:
      - "8080:8080"
    networks:
      - chakall-network
    depends_on:
      - oracle-db
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local

networks:
  chakall-network:
    driver: bridge

# Instrucciones de uso:
# 1. docker-compose up -d
# 2. Esperar que el contenedor esté healthy
# 3. Conectar usando: localhost:1521/XE
# 4. Usuario: system, Contraseña: ChakallPassword123
# 5. Ejecutar el script oracle_setup.sql
